### ISSUE TITLE
import instead of require

### ISSUE THREAD

**Issue by dav1app** [apivideo/api.video-nodejs-client#106]
**Describe the bug**
ESLINT
```
5:24  error  Require statement not part of import statement  @typescript-eslint/no-var-requires
```

TS
```
This module can only be referenced with ECMAScript imports/exports by turning on the 'esModuleInterop' flag and referencing its default export.
```

Allow users to natively use `import` instead of `require`. 

**To Reproduce**
-  `import * as ApiVideoClient from '@api.video/nodejs-client' ` 
-  `import ApiVideoClient from  '@api.video/nodejs-client' `
-  `import { ApiVideoClient } from  '@api.video/nodejs-client' `

**Environment (please complete the following information):**
- Node.js version:  v14 + TS 
- API client version:  Latest (2.2.9)

**Comment by olivierapivideo** [comment]
Hi @dav1app ,

Thanks for having reported this issues. We are going to have a look quickly. We will come back to you in the coming days.

**Comment by olivierapivideo** [comment]
Hi @dav1app,

We have release a v2.3.1. You should now be able to do:
```js
import ApiVideoClient from "@api.video/nodejs-client";
```

Can you confirm that it solves the issue?
